// gen-newsdays generates a news-days file for use with the donchian-v5/v6
// strategies (news_days_file param).
//
// Events included:
//   - NFP: US Non-Farm Payrolls — first Friday of each month (algorithmic,
//     exact).
//   - FOMC: Federal Open Market Committee decision day — hardcoded for
//     2005-2026 from the Fed's published calendar.  Emergency meetings are
//     included.  Dates are the announcement day (second day of 2-day meeting,
//     or single-day meeting date).
//
// Usage:
//
//	gen-newsdays [flags]
//	  --from  int    first year (default 2015)
//	  --to    int    last year, inclusive (default 2025)
//	  --types string comma-separated event types: nfp,fomc (default "nfp,fomc")
//	  --out   string output file path; "-" or empty = stdout
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

func main() {
	from := flag.Int("from", 2015, "first year (inclusive)")
	to := flag.Int("to", 2025, "last year (inclusive)")
	types := flag.String("types", "nfp,fomc", "comma-separated event types: nfp,fomc")
	out := flag.String("out", "", "output file path; empty = stdout")
	flag.Parse()

	wantNFP := false
	wantFOMC := false
	for _, t := range strings.Split(*types, ",") {
		switch strings.TrimSpace(strings.ToLower(t)) {
		case "nfp":
			wantNFP = true
		case "fomc":
			wantFOMC = true
		}
	}

	// Collect dates as a set to deduplicate (NFP can land on an FOMC day).
	dateMap := map[string]string{} // YYYY-MM-DD → label(s)

	add := func(t time.Time, label string) {
		k := t.UTC().Format("2006-01-02")
		if existing, ok := dateMap[k]; ok {
			dateMap[k] = existing + "," + label
		} else {
			dateMap[k] = label
		}
	}

	if wantNFP {
		for y := *from; y <= *to; y++ {
			for m := 1; m <= 12; m++ {
				add(firstFriday(y, m), "NFP")
			}
		}
	}

	if wantFOMC {
		for _, d := range fomcDates {
			t, err := time.Parse("2006-01-02", d)
			if err != nil {
				continue
			}
			if t.Year() < *from || t.Year() > *to {
				continue
			}
			add(t, "FOMC")
		}
	}

	// Sort keys.
	keys := make([]string, 0, len(dateMap))
	for k := range dateMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Write output.
	w := bufio.NewWriter(os.Stdout)
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-newsdays: %v\n", err)
			os.Exit(1)
		}
		defer f.Close()
		w = bufio.NewWriter(f)
	}

	fmt.Fprintf(w, "# News days generated by gen-newsdays\n")
	fmt.Fprintf(w, "# types=%s  from=%d  to=%d\n", *types, *from, *to)
	fmt.Fprintf(w, "# Format: YYYY-MM-DD  # event\n#\n")

	prevYear := 0
	for _, k := range keys {
		t, _ := time.Parse("2006-01-02", k)
		if t.Year() != prevYear {
			fmt.Fprintf(w, "\n# %d\n", t.Year())
			prevYear = t.Year()
		}
		fmt.Fprintf(w, "%s   # %s\n", k, dateMap[k])
	}
	w.Flush()
}

// firstFriday returns the first Friday of the given month (UTC midnight).
// Unix epoch (1970-01-01) was a Thursday so weekday arithmetic is stable.
func firstFriday(year, month int) time.Time {
	d := time.Date(year, time.Month(month), 1, 0, 0, 0, 0, time.UTC)
	for d.Weekday() != time.Friday {
		d = d.AddDate(0, 0, 1)
	}
	return d
}

// fomcDates lists FOMC announcement days (UTC date) from the Fed's published
// calendar.  Emergency meetings are included.  Source: federalreserve.gov
// meeting calendars.  Dates marked (*) are projected/approximate.
var fomcDates = []string{
	// 2005
	"2005-01-26", "2005-03-22", "2005-05-03", "2005-06-30",
	"2005-08-09", "2005-09-20", "2005-11-01", "2005-12-13",
	// 2006
	"2006-01-31", "2006-03-28", "2006-05-10", "2006-06-29",
	"2006-08-08", "2006-09-20", "2006-10-25", "2006-12-12",
	// 2007
	"2007-01-31", "2007-03-21", "2007-05-09", "2007-06-28",
	"2007-08-07", "2007-09-18", "2007-10-31", "2007-12-11",
	// 2008 — includes two emergency cuts
	"2008-01-22", "2008-01-30", "2008-03-18", "2008-04-30",
	"2008-06-25", "2008-08-05", "2008-09-16", "2008-10-08",
	"2008-10-29", "2008-12-16",
	// 2009
	"2009-01-28", "2009-03-18", "2009-04-29", "2009-06-24",
	"2009-08-12", "2009-09-23", "2009-11-04", "2009-12-16",
	// 2010
	"2010-01-27", "2010-03-16", "2010-04-28", "2010-06-23",
	"2010-08-10", "2010-09-21", "2010-11-03", "2010-12-14",
	// 2011
	"2011-01-26", "2011-03-15", "2011-04-27", "2011-06-22",
	"2011-08-09", "2011-09-21", "2011-11-02", "2011-12-13",
	// 2012
	"2012-01-25", "2012-03-13", "2012-04-25", "2012-06-20",
	"2012-08-01", "2012-09-13", "2012-10-24", "2012-12-12",
	// 2013
	"2013-01-30", "2013-03-20", "2013-05-01", "2013-06-19",
	"2013-07-31", "2013-09-18", "2013-10-30", "2013-12-18",
	// 2014
	"2014-01-29", "2014-03-19", "2014-04-30", "2014-06-18",
	"2014-07-30", "2014-09-17", "2014-10-29", "2014-12-17",
	// 2015
	"2015-01-28", "2015-03-18", "2015-04-29", "2015-06-17",
	"2015-07-29", "2015-09-17", "2015-10-28", "2015-12-16",
	// 2016
	"2016-01-27", "2016-03-16", "2016-04-27", "2016-06-15",
	"2016-07-27", "2016-09-21", "2016-11-02", "2016-12-14",
	// 2017
	"2017-02-01", "2017-03-15", "2017-05-03", "2017-06-14",
	"2017-07-26", "2017-09-20", "2017-11-01", "2017-12-13",
	// 2018
	"2018-01-31", "2018-03-21", "2018-05-02", "2018-06-13",
	"2018-08-01", "2018-09-26", "2018-11-08", "2018-12-19",
	// 2019
	"2019-01-30", "2019-03-20", "2019-05-01", "2019-06-19",
	"2019-07-31", "2019-09-18", "2019-10-30", "2019-12-11",
	// 2020 — two emergency cuts in March
	"2020-01-29", "2020-03-03", "2020-03-15", "2020-04-29",
	"2020-06-10", "2020-07-29", "2020-09-16", "2020-11-05",
	"2020-12-16",
	// 2021
	"2021-01-27", "2021-03-17", "2021-04-28", "2021-06-16",
	"2021-07-28", "2021-09-22", "2021-11-03", "2021-12-15",
	// 2022
	"2022-01-26", "2022-03-16", "2022-05-04", "2022-06-15",
	"2022-07-27", "2022-09-21", "2022-11-02", "2022-12-14",
	// 2023
	"2023-02-01", "2023-03-22", "2023-05-03", "2023-06-14",
	"2023-07-26", "2023-09-20", "2023-11-01", "2023-12-13",
	// 2024
	"2024-01-31", "2024-03-20", "2024-05-01", "2024-06-12",
	"2024-07-31", "2024-09-18", "2024-11-07", "2024-12-18",
	// 2025
	"2025-01-29", "2025-03-19", "2025-05-07", "2025-06-18",
	"2025-07-30", "2025-09-17", "2025-10-29", "2025-12-10",
	// 2026 (projected *)
	"2026-01-28", "2026-03-18", "2026-04-29", "2026-06-17",
	"2026-07-29", "2026-09-16", "2026-10-28", "2026-12-09",
}
