// Strategy Protocol v1 (issue #377, ADR-062).
//
// This schema is the wire boundary for an out-of-process external
// strategy: the Trader host process is the gRPC server
// (StrategyHostService); an external strategy process is the gRPC
// client that dials in over a Unix-domain socket. See ADR-062
// (docs/arch/adr-062-external-strategy-protocol-v1.org) for the full
// architecture and the reasoning behind every decision restated in
// comments below.
//
// Nothing in this file names a Trader domain type directly (order.
// Intent, instrument.ID, num.Price, and so on): every field here is a
// deliberately narrow wire representation of the piece of a domain
// value this protocol actually needs to carry, translated by a
// conversion layer outside this package (issue #378) — never a
// generated alias standing in for the domain type itself
// (package-boundaries.org rule 7).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: strategy.proto

package strategyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IntervalUnit mirrors marketdata.Unit's four defined values.
type IntervalUnit int32

const (
	IntervalUnit_INTERVAL_UNIT_UNSPECIFIED IntervalUnit = 0
	IntervalUnit_INTERVAL_UNIT_MINUTE      IntervalUnit = 1
	IntervalUnit_INTERVAL_UNIT_HOUR        IntervalUnit = 2
	IntervalUnit_INTERVAL_UNIT_DAY         IntervalUnit = 3
	IntervalUnit_INTERVAL_UNIT_WEEK        IntervalUnit = 4
)

// Enum value maps for IntervalUnit.
var (
	IntervalUnit_name = map[int32]string{
		0: "INTERVAL_UNIT_UNSPECIFIED",
		1: "INTERVAL_UNIT_MINUTE",
		2: "INTERVAL_UNIT_HOUR",
		3: "INTERVAL_UNIT_DAY",
		4: "INTERVAL_UNIT_WEEK",
	}
	IntervalUnit_value = map[string]int32{
		"INTERVAL_UNIT_UNSPECIFIED": 0,
		"INTERVAL_UNIT_MINUTE":      1,
		"INTERVAL_UNIT_HOUR":        2,
		"INTERVAL_UNIT_DAY":         3,
		"INTERVAL_UNIT_WEEK":        4,
	}
)

func (x IntervalUnit) Enum() *IntervalUnit {
	p := new(IntervalUnit)
	*p = x
	return p
}

func (x IntervalUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntervalUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_proto_enumTypes[0].Descriptor()
}

func (IntervalUnit) Type() protoreflect.EnumType {
	return &file_strategy_proto_enumTypes[0]
}

func (x IntervalUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntervalUnit.Descriptor instead.
func (IntervalUnit) EnumDescriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

// Side mirrors order.Side (Buy/Sell) — the transaction direction a
// DescribedIntent's own Kind requires it for (below).
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_proto_enumTypes[1].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_strategy_proto_enumTypes[1]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

// PositionSide mirrors order.PositionSide. Flat is deliberately the
// same zero value the Go type uses, so an omitted/default field reads
// as "no position" on both sides without a separate presence flag.
type PositionSide int32

const (
	PositionSide_POSITION_SIDE_FLAT  PositionSide = 0
	PositionSide_POSITION_SIDE_LONG  PositionSide = 1
	PositionSide_POSITION_SIDE_SHORT PositionSide = 2
)

// Enum value maps for PositionSide.
var (
	PositionSide_name = map[int32]string{
		0: "POSITION_SIDE_FLAT",
		1: "POSITION_SIDE_LONG",
		2: "POSITION_SIDE_SHORT",
	}
	PositionSide_value = map[string]int32{
		"POSITION_SIDE_FLAT":  0,
		"POSITION_SIDE_LONG":  1,
		"POSITION_SIDE_SHORT": 2,
	}
)

func (x PositionSide) Enum() *PositionSide {
	p := new(PositionSide)
	*p = x
	return p
}

func (x PositionSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionSide) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_proto_enumTypes[2].Descriptor()
}

func (PositionSide) Type() protoreflect.EnumType {
	return &file_strategy_proto_enumTypes[2]
}

func (x PositionSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionSide.Descriptor instead.
func (PositionSide) EnumDescriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

// IntentKind mirrors order.IntentKind's five defined values,
// including IntentEnterWithStop (ADR-059) — PR #386 review on the
// preceding ADR-062 caught an earlier omission of exactly this kind
// from the design's own described-intent vocabulary; this schema does
// not repeat that gap.
type IntentKind int32

const (
	IntentKind_INTENT_KIND_UNSPECIFIED     IntentKind = 0
	IntentKind_INTENT_KIND_ENTER           IntentKind = 1
	IntentKind_INTENT_KIND_EXIT            IntentKind = 2
	IntentKind_INTENT_KIND_ADJUST_STOP     IntentKind = 3
	IntentKind_INTENT_KIND_TARGET_EXPOSURE IntentKind = 4
	IntentKind_INTENT_KIND_ENTER_WITH_STOP IntentKind = 5
)

// Enum value maps for IntentKind.
var (
	IntentKind_name = map[int32]string{
		0: "INTENT_KIND_UNSPECIFIED",
		1: "INTENT_KIND_ENTER",
		2: "INTENT_KIND_EXIT",
		3: "INTENT_KIND_ADJUST_STOP",
		4: "INTENT_KIND_TARGET_EXPOSURE",
		5: "INTENT_KIND_ENTER_WITH_STOP",
	}
	IntentKind_value = map[string]int32{
		"INTENT_KIND_UNSPECIFIED":     0,
		"INTENT_KIND_ENTER":           1,
		"INTENT_KIND_EXIT":            2,
		"INTENT_KIND_ADJUST_STOP":     3,
		"INTENT_KIND_TARGET_EXPOSURE": 4,
		"INTENT_KIND_ENTER_WITH_STOP": 5,
	}
)

func (x IntentKind) Enum() *IntentKind {
	p := new(IntentKind)
	*p = x
	return p
}

func (x IntentKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentKind) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_proto_enumTypes[3].Descriptor()
}

func (IntentKind) Type() protoreflect.EnumType {
	return &file_strategy_proto_enumTypes[3]
}

func (x IntentKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentKind.Descriptor instead.
func (IntentKind) EnumDescriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

// Capability is v1's negotiable Handshake capability set. FILL_HANDLER
// is the only defined value: it is the sole in-process strategy
// optional capability actually published today (ADR-060). Adding a
// second capability value here (for a future AccountEventHandler or
// StateManager, once either is published in-process) is an additive,
// wire-compatible v1 change, not a v2 break.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED  Capability = 0
	Capability_CAPABILITY_FILL_HANDLER Capability = 1
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_FILL_HANDLER",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":  0,
		"CAPABILITY_FILL_HANDLER": 1,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_proto_enumTypes[4].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_strategy_proto_enumTypes[4]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{4}
}

// ErrorCode is v1's small, closed structured-error vocabulary — a
// caller branches on Code, never parses Message text. New codes may
// be added additively within v1; existing codes are never renumbered
// or repurposed.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED               ErrorCode = 0
	ErrorCode_ERROR_CODE_PROTOCOL_VERSION_MISMATCH ErrorCode = 1
	ErrorCode_ERROR_CODE_CAPABILITY_MISMATCH       ErrorCode = 2
	// ERROR_CODE_UNKNOWN_CALLBACK: a GetHistoryBarsRequest named a
	// callback_sequence the adapter is not currently waiting on a
	// response for (ADR-062's own GetHistoryBars view-cutoff binding).
	ErrorCode_ERROR_CODE_UNKNOWN_CALLBACK ErrorCode = 3
	// ERROR_CODE_REQUIREMENT_NOT_DECLARED: a GetHistoryBarsRequest named
	// an instrument/interval outside the Handshake-declared Requirements.
	ErrorCode_ERROR_CODE_REQUIREMENT_NOT_DECLARED ErrorCode = 4
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED        ErrorCode = 5
	ErrorCode_ERROR_CODE_INVALID_DESCRIBED_INTENT ErrorCode = 6
	// ERROR_CODE_UNKNOWN_SESSION: a Run or GetHistoryBars call carried a
	// session_id that does not match any Handshake this connection
	// completed (review finding: UNSPECIFIED must never double as
	// "session not found").
	ErrorCode_ERROR_CODE_UNKNOWN_SESSION ErrorCode = 7
	// ERROR_CODE_CALLBACK_FAILED: the guest's own OnBar or OnFill
	// handler returned an error (review finding: a dedicated code,
	// reserved for exactly this, rather than reusing UNSPECIFIED — which
	// SessionEnd's own zero value already means "normal completion,"
	// not "something failed but we don't know what").
	ErrorCode_ERROR_CODE_CALLBACK_FAILED ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_PROTOCOL_VERSION_MISMATCH",
		2: "ERROR_CODE_CAPABILITY_MISMATCH",
		3: "ERROR_CODE_UNKNOWN_CALLBACK",
		4: "ERROR_CODE_REQUIREMENT_NOT_DECLARED",
		5: "ERROR_CODE_DEADLINE_EXCEEDED",
		6: "ERROR_CODE_INVALID_DESCRIBED_INTENT",
		7: "ERROR_CODE_UNKNOWN_SESSION",
		8: "ERROR_CODE_CALLBACK_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":               0,
		"ERROR_CODE_PROTOCOL_VERSION_MISMATCH": 1,
		"ERROR_CODE_CAPABILITY_MISMATCH":       2,
		"ERROR_CODE_UNKNOWN_CALLBACK":          3,
		"ERROR_CODE_REQUIREMENT_NOT_DECLARED":  4,
		"ERROR_CODE_DEADLINE_EXCEEDED":         5,
		"ERROR_CODE_INVALID_DESCRIBED_INTENT":  6,
		"ERROR_CODE_UNKNOWN_SESSION":           7,
		"ERROR_CODE_CALLBACK_FAILED":           8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_proto_enumTypes[5].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_strategy_proto_enumTypes[5]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{5}
}

// Error is a structured error value carried inside a message field
// (for example SessionEnd, below) — distinct from, and not a
// replacement for, gRPC's own per-RPC status/error mechanism, which
// unary RPCs (Handshake, GetHistoryBars) continue to use directly.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=trader.strategy.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Interval mirrors marketdata.Interval (a Unit and a count — never a
// parsed string, per marketdata.Interval's own documented contract).
type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          IntervalUnit           `protobuf:"varint,1,opt,name=unit,proto3,enum=trader.strategy.v1.IntervalUnit" json:"unit,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *Interval) GetUnit() IntervalUnit {
	if x != nil {
		return x.Unit
	}
	return IntervalUnit_INTERVAL_UNIT_UNSPECIFIED
}

func (x *Interval) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// DataRequirement mirrors strategy.DataRequirement.
type DataRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instrument_id is instrument.ID's own canonical String() form (for
	// example "fx:EUR/USD"), the same text instrument.ID.MarshalJSON
	// already produces — never a raw provider symbol.
	InstrumentId  string    `protobuf:"bytes,1,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Interval      *Interval `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	WarmupBars    int32     `protobuf:"varint,3,opt,name=warmup_bars,json=warmupBars,proto3" json:"warmup_bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequirement) Reset() {
	*x = DataRequirement{}
	mi := &file_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequirement) ProtoMessage() {}

func (x *DataRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequirement.ProtoReflect.Descriptor instead.
func (*DataRequirement) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *DataRequirement) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *DataRequirement) GetInterval() *Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *DataRequirement) GetWarmupBars() int32 {
	if x != nil {
		return x.WarmupBars
	}
	return 0
}

// StrategyDescriptor mirrors strategy.Descriptor.
type StrategyDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Requirements  []*DataRequirement     `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyDescriptor) Reset() {
	*x = StrategyDescriptor{}
	mi := &file_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyDescriptor) ProtoMessage() {}

func (x *StrategyDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyDescriptor.ProtoReflect.Descriptor instead.
func (*StrategyDescriptor) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *StrategyDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StrategyDescriptor) GetRequirements() []*DataRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

// Bar mirrors marketdata.Bar's own exported fields.
type Bar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// time_unix_nanos is Bar.Time, UTC, as nanoseconds since the Unix
	// epoch — never reconstructed from array position or fixed-duration
	// arithmetic on the receiving side (marketdata.Bar's own documented
	// invariant), only carried verbatim.
	TimeUnixNanos int64  `protobuf:"varint,1,opt,name=time_unix_nanos,json=timeUnixNanos,proto3" json:"time_unix_nanos,omitempty"`
	Open          string `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	High          string `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           string `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         string `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	AvgSpread     string `protobuf:"bytes,6,opt,name=avg_spread,json=avgSpread,proto3" json:"avg_spread,omitempty"`
	MaxSpread     string `protobuf:"bytes,7,opt,name=max_spread,json=maxSpread,proto3" json:"max_spread,omitempty"`
	Ticks         int64  `protobuf:"varint,8,opt,name=ticks,proto3" json:"ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *Bar) GetTimeUnixNanos() int64 {
	if x != nil {
		return x.TimeUnixNanos
	}
	return 0
}

func (x *Bar) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Bar) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Bar) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Bar) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Bar) GetAvgSpread() string {
	if x != nil {
		return x.AvgSpread
	}
	return ""
}

func (x *Bar) GetMaxSpread() string {
	if x != nil {
		return x.MaxSpread
	}
	return ""
}

func (x *Bar) GetTicks() int64 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

// PositionSnapshot mirrors exactly the order.Position fields a
// current in-process strategy actually reads (issue #377's own "no
// speculative surfaces beyond current concrete consumers": both
// strategy/smatrend and strategy/emacross read only Listing.
// InstrumentID(), Side, and AvgPrice from a Position — neither reads
// Quantity at all). AccountID, Quantity, and the full Listing (Spec,
// Provider, Symbol, Tradable) are deliberately omitted from v1
// (review finding: an earlier draft included Quantity despite no
// concrete consumer reading it, contradicting this message's own
// "exactly" minimum-slice rationale).
type PositionSnapshot struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstrumentId string                 `protobuf:"bytes,1,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Side         PositionSide           `protobuf:"varint,2,opt,name=side,proto3,enum=trader.strategy.v1.PositionSide" json:"side,omitempty"`
	// avg_price is empty when side is POSITION_SIDE_FLAT, mirroring
	// order.Position's own "nil exactly when Side is Flat" invariant.
	AvgPrice      string `protobuf:"bytes,3,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionSnapshot) Reset() {
	*x = PositionSnapshot{}
	mi := &file_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSnapshot) ProtoMessage() {}

func (x *PositionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSnapshot.ProtoReflect.Descriptor instead.
func (*PositionSnapshot) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *PositionSnapshot) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *PositionSnapshot) GetSide() PositionSide {
	if x != nil {
		return x.Side
	}
	return PositionSide_POSITION_SIDE_FLAT
}

func (x *PositionSnapshot) GetAvgPrice() string {
	if x != nil {
		return x.AvgPrice
	}
	return ""
}

// AccountSnapshot is deliberately the minimum slice of account.
// Snapshot any current in-process strategy actually reads: every
// published strategy today reads only View.Account().Positions() —
// nothing else. Equity, RealizedPnL, and UnrealizedPnL are
// deliberately omitted from v1 (review finding: an earlier draft
// included them as "cheap, broadly useful scalars," but that is
// exactly the speculative-surface reasoning issue #377 asks this
// schema to avoid — removing a field later, once a real consumer
// exists, is a breaking v2 change, while adding one is a free,
// additive v1 change). OpenOrders, CashBalances, BuyingPower, and
// MarginUsed/MarginAvailable remain omitted for the same reason.
// account_id/currency/as_of_unix_nanos are kept as cheap identity/
// provenance fields, the same category BarEvent.instrument_id and
// FillEvent.order_id already are elsewhere in this schema, not
// trading-state surfaces.
type AccountSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	AsOfUnixNanos int64                  `protobuf:"varint,3,opt,name=as_of_unix_nanos,json=asOfUnixNanos,proto3" json:"as_of_unix_nanos,omitempty"`
	Positions     []*PositionSnapshot    `protobuf:"bytes,4,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSnapshot) Reset() {
	*x = AccountSnapshot{}
	mi := &file_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSnapshot) ProtoMessage() {}

func (x *AccountSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSnapshot.ProtoReflect.Descriptor instead.
func (*AccountSnapshot) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *AccountSnapshot) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountSnapshot) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountSnapshot) GetAsOfUnixNanos() int64 {
	if x != nil {
		return x.AsOfUnixNanos
	}
	return 0
}

func (x *AccountSnapshot) GetPositions() []*PositionSnapshot {
	if x != nil {
		return x.Positions
	}
	return nil
}

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// strategy_descriptor is named to avoid colliding with proto-gen-go's
	// own generated Descriptor() method on every message type — not
	// "descriptor".
	StrategyDescriptor *StrategyDescriptor `protobuf:"bytes,2,opt,name=strategy_descriptor,json=strategyDescriptor,proto3" json:"strategy_descriptor,omitempty"`
	Capabilities       []Capability        `protobuf:"varint,3,rep,packed,name=capabilities,proto3,enum=trader.strategy.v1.Capability" json:"capabilities,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_strategy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{7}
}

func (x *HandshakeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeRequest) GetStrategyDescriptor() *StrategyDescriptor {
	if x != nil {
		return x.StrategyDescriptor
	}
	return nil
}

func (x *HandshakeRequest) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []Capability           `protobuf:"varint,3,rep,packed,name=capabilities,proto3,enum=trader.strategy.v1.Capability" json:"capabilities,omitempty"`
	// reject_reason is set only when accepted is false — for example on
	// a protocol version or capability mismatch the host cannot bridge.
	RejectReason *Error `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	// session_id is a host-issued, opaque token uniquely identifying
	// this accepted Handshake, set only when accepted is true (review
	// finding: StrategyHostService allows several independent
	// connections/strategies, and BarEvent.sequence is only unique
	// *within* one session — nothing previously bound a Run stream or a
	// GetHistoryBarsRequest to the specific Handshake/frozen-view state
	// it belongs to). The guest must present this exact value in
	// RunOpen (below) and in every GetHistoryBarsRequest; a value that
	// does not match an active session is rejected
	// (ERROR_CODE_UNKNOWN_SESSION).
	SessionId     string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_strategy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HandshakeResponse) GetRejectReason() *Error {
	if x != nil {
		return x.RejectReason
	}
	return nil
}

func (x *HandshakeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// RunOpen is the Run stream's own mandatory first client->server
// message (above).
type RunOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunOpen) Reset() {
	*x = RunOpen{}
	mi := &file_strategy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOpen) ProtoMessage() {}

func (x *RunOpen) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOpen.ProtoReflect.Descriptor instead.
func (*RunOpen) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{9}
}

func (x *RunOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStart struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RunId              string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StartTimeUnixNanos int64                  `protobuf:"varint,2,opt,name=start_time_unix_nanos,json=startTimeUnixNanos,proto3" json:"start_time_unix_nanos,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_strategy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{10}
}

func (x *SessionStart) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SessionStart) GetStartTimeUnixNanos() int64 {
	if x != nil {
		return x.StartTimeUnixNanos
	}
	return 0
}

// SessionEnd is the Run stream's own terminal server->client message,
// sent once before the host closes the stream. code/reason are the
// zero value (ERROR_CODE_UNSPECIFIED, empty string) on a normal,
// successful run completion.
type SessionEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=trader.strategy.v1.ErrorCode" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEnd) Reset() {
	*x = SessionEnd{}
	mi := &file_strategy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEnd) ProtoMessage() {}

func (x *SessionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEnd.ProtoReflect.Descriptor instead.
func (*SessionEnd) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{11}
}

func (x *SessionEnd) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *SessionEnd) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// BarEvent mirrors strategy.BarEvent plus the inline account snapshot
// ADR-062's own View decision requires: the account snapshot is
// carried inline here, computed by the host before it writes this
// message, so it reflects the identical no-lookahead cutoff the
// host's own frozen View already enforces for an in-process strategy.
type BarEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sequence uniquely identifies this callback within the session
	// (monotonically increasing) — echoed back in OnBarResponse, and
	// usable as GetHistoryBarsRequest.callback_sequence while this bar's
	// own response is still outstanding.
	Sequence      uint64           `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	InstrumentId  string           `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Interval      *Interval        `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Bar           *Bar             `protobuf:"bytes,4,opt,name=bar,proto3" json:"bar,omitempty"`
	Account       *AccountSnapshot `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarEvent) Reset() {
	*x = BarEvent{}
	mi := &file_strategy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarEvent) ProtoMessage() {}

func (x *BarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarEvent.ProtoReflect.Descriptor instead.
func (*BarEvent) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{12}
}

func (x *BarEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BarEvent) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *BarEvent) GetInterval() *Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *BarEvent) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

func (x *BarEvent) GetAccount() *AccountSnapshot {
	if x != nil {
		return x.Account
	}
	return nil
}

// DescribedIntent is the wire shape of a guest's requested trading
// action — never a canonical order.Intent, and never carrying a real
// IntentID/EventID/CorrelationID: the host mints those through its
// own retained IntentFactory (ADR-005, ADR-062). Which of side/
// quantity/stop_price is required depends on kind, mirroring order.
// NewIntent's own validation exactly (issue #378's own job to
// enforce, not this schema's).
type DescribedIntent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Kind         IntentKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=trader.strategy.v1.IntentKind" json:"kind,omitempty"`
	InstrumentId string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Side         Side                   `protobuf:"varint,3,opt,name=side,proto3,enum=trader.strategy.v1.Side" json:"side,omitempty"`
	Quantity     string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	StopPrice    string                 `protobuf:"bytes,5,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	// correlation_token is an opaque, guest-chosen string grouping
	// multiple described intents from one callback under one real
	// CorrelationID (via the host's own IntentFactory.WithCorrelation) —
	// it carries no identity meaning of its own beyond that grouping.
	// Empty means "not grouped with any other described intent."
	CorrelationToken string `protobuf:"bytes,6,opt,name=correlation_token,json=correlationToken,proto3" json:"correlation_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DescribedIntent) Reset() {
	*x = DescribedIntent{}
	mi := &file_strategy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribedIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribedIntent) ProtoMessage() {}

func (x *DescribedIntent) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribedIntent.ProtoReflect.Descriptor instead.
func (*DescribedIntent) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{13}
}

func (x *DescribedIntent) GetKind() IntentKind {
	if x != nil {
		return x.Kind
	}
	return IntentKind_INTENT_KIND_UNSPECIFIED
}

func (x *DescribedIntent) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *DescribedIntent) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *DescribedIntent) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *DescribedIntent) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *DescribedIntent) GetCorrelationToken() string {
	if x != nil {
		return x.CorrelationToken
	}
	return ""
}

// DescribedSignal mirrors journal.Signal verbatim (issue #384's own
// deterministic-equivalence requirement, ADR-062): a plain,
// string-keyed evidence bag with no translation needed, written by
// the host through its own retained env.Journal exactly as a
// DescribedIntent is turned into a canonical order.Intent through
// env.Intents.
type DescribedSignal struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Strategy string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Values   map[string]string      `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// correlation_token names the same DescribedIntent.correlation_token
	// this signal explains, if any (review finding: strategy/smatrend's
	// own recordSignal records a signal's journal.Record.Metadata.
	// CorrelationID as the *emitted intent's own real CorrelationID*
	// when one was emitted this bar, and the zero value otherwise —
	// strategy/smatrend/strategy.go's own recordSignal, "var corr id.
	// CorrelationID; if len(intents) > 0 { corr = intents[0].Metadata.
	// CorrelationID }"). The host reproduces this exactly: when this
	// token matches a token used by one or more of this same
	// OnBarResponse's own intents, the host uses that group's own real,
	// already-minted CorrelationID; an empty token (or one matching no
	// intent this callback) means the zero CorrelationID, matching
	// smatrend's own "no intents this bar" case.
	CorrelationToken string `protobuf:"bytes,3,opt,name=correlation_token,json=correlationToken,proto3" json:"correlation_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DescribedSignal) Reset() {
	*x = DescribedSignal{}
	mi := &file_strategy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribedSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribedSignal) ProtoMessage() {}

func (x *DescribedSignal) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribedSignal.ProtoReflect.Descriptor instead.
func (*DescribedSignal) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{14}
}

func (x *DescribedSignal) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *DescribedSignal) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DescribedSignal) GetCorrelationToken() string {
	if x != nil {
		return x.CorrelationToken
	}
	return ""
}

// OnBarResponse is the guest's own response to one BarEvent. Empty
// intents/signals lists are valid, explicit "nothing this bar"
// responses, not a lack of one. error is set only when the guest's
// own OnBar handler itself returned an error (review finding: an
// earlier draft had no way to represent this — a failed callback
// would have had to collapse into stream EOF/a gRPC status, losing
// the structured failure and giving ExternalStrategyAdapter no
// predictable way to report it, unlike OnFillResponse, which already
// had this field). When error is set, intents/signals must both be
// empty — a failed callback contributes nothing.
type OnBarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Intents       []*DescribedIntent     `protobuf:"bytes,2,rep,name=intents,proto3" json:"intents,omitempty"`
	Signals       []*DescribedSignal     `protobuf:"bytes,3,rep,name=signals,proto3" json:"signals,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnBarResponse) Reset() {
	*x = OnBarResponse{}
	mi := &file_strategy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnBarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnBarResponse) ProtoMessage() {}

func (x *OnBarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnBarResponse.ProtoReflect.Descriptor instead.
func (*OnBarResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{15}
}

func (x *OnBarResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OnBarResponse) GetIntents() []*DescribedIntent {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *OnBarResponse) GetSignals() []*DescribedSignal {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *OnBarResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// FillEvent mirrors strategy.FillEvent/order.Fill's own identity-
// relevant fields, delivered only when CAPABILITY_FILL_HANDLER was
// negotiated at Handshake (ADR-060, ADR-062's own capability-wrapper
// design).
type FillEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	InstrumentId  string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Side          Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=trader.strategy.v1.Side" json:"side,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CorrelationId string                 `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId   string                 `protobuf:"bytes,8,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	Account       *AccountSnapshot       `protobuf:"bytes,9,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillEvent) Reset() {
	*x = FillEvent{}
	mi := &file_strategy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillEvent) ProtoMessage() {}

func (x *FillEvent) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillEvent.ProtoReflect.Descriptor instead.
func (*FillEvent) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{16}
}

func (x *FillEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FillEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *FillEvent) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *FillEvent) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *FillEvent) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *FillEvent) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *FillEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *FillEvent) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *FillEvent) GetAccount() *AccountSnapshot {
	if x != nil {
		return x.Account
	}
	return nil
}

// OnFillResponse is the guest's own response to one FillEvent.
// strategy.FillHandler.OnFill returns only error, never intents
// (ADR-060's own deliberate signature), so this carries no described
// intents or signals — only the sequence being acknowledged, plus an
// error when the guest's own OnFill returned one.
type OnFillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnFillResponse) Reset() {
	*x = OnFillResponse{}
	mi := &file_strategy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnFillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnFillResponse) ProtoMessage() {}

func (x *OnFillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnFillResponse.ProtoReflect.Descriptor instead.
func (*OnFillResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{17}
}

func (x *OnFillResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OnFillResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// RunServerMessage is one message the host writes down the Run
// stream. Exactly one field is set, matching Kind's own discriminated-
// envelope convention already established elsewhere in this codebase
// (journal.Record, broker.Event).
type RunServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunServerMessage_SessionStart
	//	*RunServerMessage_BarEvent
	//	*RunServerMessage_FillEvent
	//	*RunServerMessage_SessionEnd
	Payload       isRunServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunServerMessage) Reset() {
	*x = RunServerMessage{}
	mi := &file_strategy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunServerMessage) ProtoMessage() {}

func (x *RunServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunServerMessage.ProtoReflect.Descriptor instead.
func (*RunServerMessage) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{18}
}

func (x *RunServerMessage) GetPayload() isRunServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunServerMessage) GetSessionStart() *SessionStart {
	if x != nil {
		if x, ok := x.Payload.(*RunServerMessage_SessionStart); ok {
			return x.SessionStart
		}
	}
	return nil
}

func (x *RunServerMessage) GetBarEvent() *BarEvent {
	if x != nil {
		if x, ok := x.Payload.(*RunServerMessage_BarEvent); ok {
			return x.BarEvent
		}
	}
	return nil
}

func (x *RunServerMessage) GetFillEvent() *FillEvent {
	if x != nil {
		if x, ok := x.Payload.(*RunServerMessage_FillEvent); ok {
			return x.FillEvent
		}
	}
	return nil
}

func (x *RunServerMessage) GetSessionEnd() *SessionEnd {
	if x != nil {
		if x, ok := x.Payload.(*RunServerMessage_SessionEnd); ok {
			return x.SessionEnd
		}
	}
	return nil
}

type isRunServerMessage_Payload interface {
	isRunServerMessage_Payload()
}

type RunServerMessage_SessionStart struct {
	SessionStart *SessionStart `protobuf:"bytes,1,opt,name=session_start,json=sessionStart,proto3,oneof"`
}

type RunServerMessage_BarEvent struct {
	BarEvent *BarEvent `protobuf:"bytes,2,opt,name=bar_event,json=barEvent,proto3,oneof"`
}

type RunServerMessage_FillEvent struct {
	FillEvent *FillEvent `protobuf:"bytes,3,opt,name=fill_event,json=fillEvent,proto3,oneof"`
}

type RunServerMessage_SessionEnd struct {
	SessionEnd *SessionEnd `protobuf:"bytes,4,opt,name=session_end,json=sessionEnd,proto3,oneof"`
}

func (*RunServerMessage_SessionStart) isRunServerMessage_Payload() {}

func (*RunServerMessage_BarEvent) isRunServerMessage_Payload() {}

func (*RunServerMessage_FillEvent) isRunServerMessage_Payload() {}

func (*RunServerMessage_SessionEnd) isRunServerMessage_Payload() {}

// RunClientMessage is one message the guest writes down the Run
// stream. run_open is always the first message on the stream and
// never appears again after that (above).
type RunClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunClientMessage_RunOpen
	//	*RunClientMessage_OnBarResponse
	//	*RunClientMessage_OnFillResponse
	Payload       isRunClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunClientMessage) Reset() {
	*x = RunClientMessage{}
	mi := &file_strategy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunClientMessage) ProtoMessage() {}

func (x *RunClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunClientMessage.ProtoReflect.Descriptor instead.
func (*RunClientMessage) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{19}
}

func (x *RunClientMessage) GetPayload() isRunClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunClientMessage) GetRunOpen() *RunOpen {
	if x != nil {
		if x, ok := x.Payload.(*RunClientMessage_RunOpen); ok {
			return x.RunOpen
		}
	}
	return nil
}

func (x *RunClientMessage) GetOnBarResponse() *OnBarResponse {
	if x != nil {
		if x, ok := x.Payload.(*RunClientMessage_OnBarResponse); ok {
			return x.OnBarResponse
		}
	}
	return nil
}

func (x *RunClientMessage) GetOnFillResponse() *OnFillResponse {
	if x != nil {
		if x, ok := x.Payload.(*RunClientMessage_OnFillResponse); ok {
			return x.OnFillResponse
		}
	}
	return nil
}

type isRunClientMessage_Payload interface {
	isRunClientMessage_Payload()
}

type RunClientMessage_RunOpen struct {
	RunOpen *RunOpen `protobuf:"bytes,1,opt,name=run_open,json=runOpen,proto3,oneof"`
}

type RunClientMessage_OnBarResponse struct {
	OnBarResponse *OnBarResponse `protobuf:"bytes,2,opt,name=on_bar_response,json=onBarResponse,proto3,oneof"`
}

type RunClientMessage_OnFillResponse struct {
	OnFillResponse *OnFillResponse `protobuf:"bytes,3,opt,name=on_fill_response,json=onFillResponse,proto3,oneof"`
}

func (*RunClientMessage_RunOpen) isRunClientMessage_Payload() {}

func (*RunClientMessage_OnBarResponse) isRunClientMessage_Payload() {}

func (*RunClientMessage_OnFillResponse) isRunClientMessage_Payload() {}

// GetHistoryBarsRequest is bound to one specific in-flight callback's
// own frozen view, not to whatever the host's live state happens to
// be when the RPC arrives (ADR-062's own corrected View design):
// session_id must name the active session this request belongs to
// (ERROR_CODE_UNKNOWN_SESSION otherwise — review finding, above), and
// callback_sequence must name a BarEvent that session's adapter is
// still waiting on an OnBarResponse for, or the host rejects the
// request (ERROR_CODE_UNKNOWN_CALLBACK). instrument_id/interval must
// also be one of the Handshake-declared Requirements
// (ERROR_CODE_REQUIREMENT_NOT_DECLARED otherwise).
type GetHistoryBarsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CallbackSequence uint64                 `protobuf:"varint,2,opt,name=callback_sequence,json=callbackSequence,proto3" json:"callback_sequence,omitempty"`
	InstrumentId     string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Interval         *Interval              `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	// count is the number of most-recent bars requested, ending strictly
	// before the frozen callback's own current bar (never including that
	// bar itself, which BarEvent already carried) — the same "up to n
	// most-recently-closed bars, strictly before the current callback's
	// own timestamp" contract strategy.History.HistoryBars already
	// documents in-process. Fewer than count bars available (run start,
	// or before this requirement's own data begins) is not an error: the
	// response simply carries fewer bars, never padded.
	Count         int32 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryBarsRequest) Reset() {
	*x = GetHistoryBarsRequest{}
	mi := &file_strategy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryBarsRequest) ProtoMessage() {}

func (x *GetHistoryBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryBarsRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryBarsRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{20}
}

func (x *GetHistoryBarsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetHistoryBarsRequest) GetCallbackSequence() uint64 {
	if x != nil {
		return x.CallbackSequence
	}
	return 0
}

func (x *GetHistoryBarsRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *GetHistoryBarsRequest) GetInterval() *Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *GetHistoryBarsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetHistoryBarsResponse.bars is returned oldest-first (review
// finding: this must be part of the wire contract, not left to SDK
// convention — different guest implementations could otherwise
// produce opposite sequences from the identical request, silently
// changing indicator results and breaking issue #384's own
// deterministic-equivalence requirement), mirroring strategy.History.
// HistoryBars's own documented ordering exactly.
type GetHistoryBarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bars          []*Bar                 `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryBarsResponse) Reset() {
	*x = GetHistoryBarsResponse{}
	mi := &file_strategy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryBarsResponse) ProtoMessage() {}

func (x *GetHistoryBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryBarsResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryBarsResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{21}
}

func (x *GetHistoryBarsResponse) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

var File_strategy_proto protoreflect.FileDescriptor

const file_strategy_proto_rawDesc = "" +
	"\n" +
	"\x0estrategy.proto\x12\x12trader.strategy.v1\"T\n" +
	"\x05Error\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.trader.strategy.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\bInterval\x124\n" +
	"\x04unit\x18\x01 \x01(\x0e2 .trader.strategy.v1.IntervalUnitR\x04unit\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x91\x01\n" +
	"\x0fDataRequirement\x12#\n" +
	"\rinstrument_id\x18\x01 \x01(\tR\finstrumentId\x128\n" +
	"\binterval\x18\x02 \x01(\v2\x1c.trader.strategy.v1.IntervalR\binterval\x12\x1f\n" +
	"\vwarmup_bars\x18\x03 \x01(\x05R\n" +
	"warmupBars\"\x8b\x01\n" +
	"\x12StrategyDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12G\n" +
	"\frequirements\x18\x03 \x03(\v2#.trader.strategy.v1.DataRequirementR\frequirements\"\xd1\x01\n" +
	"\x03Bar\x12&\n" +
	"\x0ftime_unix_nanos\x18\x01 \x01(\x03R\rtimeUnixNanos\x12\x12\n" +
	"\x04open\x18\x02 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\tR\x05close\x12\x1d\n" +
	"\n" +
	"avg_spread\x18\x06 \x01(\tR\tavgSpread\x12\x1d\n" +
	"\n" +
	"max_spread\x18\a \x01(\tR\tmaxSpread\x12\x14\n" +
	"\x05ticks\x18\b \x01(\x03R\x05ticks\"\x8a\x01\n" +
	"\x10PositionSnapshot\x12#\n" +
	"\rinstrument_id\x18\x01 \x01(\tR\finstrumentId\x124\n" +
	"\x04side\x18\x02 \x01(\x0e2 .trader.strategy.v1.PositionSideR\x04side\x12\x1b\n" +
	"\tavg_price\x18\x03 \x01(\tR\bavgPrice\"\xb9\x01\n" +
	"\x0fAccountSnapshot\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12'\n" +
	"\x10as_of_unix_nanos\x18\x03 \x01(\x03R\rasOfUnixNanos\x12B\n" +
	"\tpositions\x18\x04 \x03(\v2$.trader.strategy.v1.PositionSnapshotR\tpositions\"\xda\x01\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12W\n" +
	"\x13strategy_descriptor\x18\x02 \x01(\v2&.trader.strategy.v1.StrategyDescriptorR\x12strategyDescriptor\x12B\n" +
	"\fcapabilities\x18\x03 \x03(\x0e2\x1e.trader.strategy.v1.CapabilityR\fcapabilities\"\xfd\x01\n" +
	"\x11HandshakeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12B\n" +
	"\fcapabilities\x18\x03 \x03(\x0e2\x1e.trader.strategy.v1.CapabilityR\fcapabilities\x12>\n" +
	"\rreject_reason\x18\x04 \x01(\v2\x19.trader.strategy.v1.ErrorR\frejectReason\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"(\n" +
	"\aRunOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"X\n" +
	"\fSessionStart\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x121\n" +
	"\x15start_time_unix_nanos\x18\x02 \x01(\x03R\x12startTimeUnixNanos\"W\n" +
	"\n" +
	"SessionEnd\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.trader.strategy.v1.ErrorCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xef\x01\n" +
	"\bBarEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x128\n" +
	"\binterval\x18\x03 \x01(\v2\x1c.trader.strategy.v1.IntervalR\binterval\x12)\n" +
	"\x03bar\x18\x04 \x01(\v2\x17.trader.strategy.v1.BarR\x03bar\x12=\n" +
	"\aaccount\x18\x05 \x01(\v2#.trader.strategy.v1.AccountSnapshotR\aaccount\"\x80\x02\n" +
	"\x0fDescribedIntent\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.trader.strategy.v1.IntentKindR\x04kind\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12,\n" +
	"\x04side\x18\x03 \x01(\x0e2\x18.trader.strategy.v1.SideR\x04side\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x1d\n" +
	"\n" +
	"stop_price\x18\x05 \x01(\tR\tstopPrice\x12+\n" +
	"\x11correlation_token\x18\x06 \x01(\tR\x10correlationToken\"\xde\x01\n" +
	"\x0fDescribedSignal\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12G\n" +
	"\x06values\x18\x02 \x03(\v2/.trader.strategy.v1.DescribedSignal.ValuesEntryR\x06values\x12+\n" +
	"\x11correlation_token\x18\x03 \x01(\tR\x10correlationToken\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\rOnBarResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12=\n" +
	"\aintents\x18\x02 \x03(\v2#.trader.strategy.v1.DescribedIntentR\aintents\x12=\n" +
	"\asignals\x18\x03 \x03(\v2#.trader.strategy.v1.DescribedSignalR\asignals\x12/\n" +
	"\x05error\x18\x04 \x01(\v2\x19.trader.strategy.v1.ErrorR\x05error\"\xd0\x02\n" +
	"\tFillEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x12,\n" +
	"\x04side\x18\x04 \x01(\x0e2\x18.trader.strategy.v1.SideR\x04side\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\b \x01(\tR\vcausationId\x12=\n" +
	"\aaccount\x18\t \x01(\v2#.trader.strategy.v1.AccountSnapshotR\aaccount\"]\n" +
	"\x0eOnFillResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x19.trader.strategy.v1.ErrorR\x05error\"\xa6\x02\n" +
	"\x10RunServerMessage\x12G\n" +
	"\rsession_start\x18\x01 \x01(\v2 .trader.strategy.v1.SessionStartH\x00R\fsessionStart\x12;\n" +
	"\tbar_event\x18\x02 \x01(\v2\x1c.trader.strategy.v1.BarEventH\x00R\bbarEvent\x12>\n" +
	"\n" +
	"fill_event\x18\x03 \x01(\v2\x1d.trader.strategy.v1.FillEventH\x00R\tfillEvent\x12A\n" +
	"\vsession_end\x18\x04 \x01(\v2\x1e.trader.strategy.v1.SessionEndH\x00R\n" +
	"sessionEndB\t\n" +
	"\apayload\"\xf4\x01\n" +
	"\x10RunClientMessage\x128\n" +
	"\brun_open\x18\x01 \x01(\v2\x1b.trader.strategy.v1.RunOpenH\x00R\arunOpen\x12K\n" +
	"\x0fon_bar_response\x18\x02 \x01(\v2!.trader.strategy.v1.OnBarResponseH\x00R\ronBarResponse\x12N\n" +
	"\x10on_fill_response\x18\x03 \x01(\v2\".trader.strategy.v1.OnFillResponseH\x00R\x0eonFillResponseB\t\n" +
	"\apayload\"\xd8\x01\n" +
	"\x15GetHistoryBarsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x11callback_sequence\x18\x02 \x01(\x04R\x10callbackSequence\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x128\n" +
	"\binterval\x18\x04 \x01(\v2\x1c.trader.strategy.v1.IntervalR\binterval\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"E\n" +
	"\x16GetHistoryBarsResponse\x12+\n" +
	"\x04bars\x18\x01 \x03(\v2\x17.trader.strategy.v1.BarR\x04bars*\x8e\x01\n" +
	"\fIntervalUnit\x12\x1d\n" +
	"\x19INTERVAL_UNIT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INTERVAL_UNIT_MINUTE\x10\x01\x12\x16\n" +
	"\x12INTERVAL_UNIT_HOUR\x10\x02\x12\x15\n" +
	"\x11INTERVAL_UNIT_DAY\x10\x03\x12\x16\n" +
	"\x12INTERVAL_UNIT_WEEK\x10\x04*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*W\n" +
	"\fPositionSide\x12\x16\n" +
	"\x12POSITION_SIDE_FLAT\x10\x00\x12\x16\n" +
	"\x12POSITION_SIDE_LONG\x10\x01\x12\x17\n" +
	"\x13POSITION_SIDE_SHORT\x10\x02*\xb5\x01\n" +
	"\n" +
	"IntentKind\x12\x1b\n" +
	"\x17INTENT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11INTENT_KIND_ENTER\x10\x01\x12\x14\n" +
	"\x10INTENT_KIND_EXIT\x10\x02\x12\x1b\n" +
	"\x17INTENT_KIND_ADJUST_STOP\x10\x03\x12\x1f\n" +
	"\x1bINTENT_KIND_TARGET_EXPOSURE\x10\x04\x12\x1f\n" +
	"\x1bINTENT_KIND_ENTER_WITH_STOP\x10\x05*E\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CAPABILITY_FILL_HANDLER\x10\x01*\xca\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12(\n" +
	"$ERROR_CODE_PROTOCOL_VERSION_MISMATCH\x10\x01\x12\"\n" +
	"\x1eERROR_CODE_CAPABILITY_MISMATCH\x10\x02\x12\x1f\n" +
	"\x1bERROR_CODE_UNKNOWN_CALLBACK\x10\x03\x12'\n" +
	"#ERROR_CODE_REQUIREMENT_NOT_DECLARED\x10\x04\x12 \n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\x05\x12'\n" +
	"#ERROR_CODE_INVALID_DESCRIBED_INTENT\x10\x06\x12\x1e\n" +
	"\x1aERROR_CODE_UNKNOWN_SESSION\x10\a\x12\x1e\n" +
	"\x1aERROR_CODE_CALLBACK_FAILED\x10\b2\xaf\x02\n" +
	"\x13StrategyHostService\x12X\n" +
	"\tHandshake\x12$.trader.strategy.v1.HandshakeRequest\x1a%.trader.strategy.v1.HandshakeResponse\x12U\n" +
	"\x03Run\x12$.trader.strategy.v1.RunClientMessage\x1a$.trader.strategy.v1.RunServerMessage(\x010\x01\x12g\n" +
	"\x0eGetHistoryBars\x12).trader.strategy.v1.GetHistoryBarsRequest\x1a*.trader.strategy.v1.GetHistoryBarsResponseB=Z;github.com/rustyeddy/trader/protocol/strategy/v1;strategyv1b\x06proto3"

var (
	file_strategy_proto_rawDescOnce sync.Once
	file_strategy_proto_rawDescData []byte
)

func file_strategy_proto_rawDescGZIP() []byte {
	file_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)))
	})
	return file_strategy_proto_rawDescData
}

var file_strategy_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_strategy_proto_goTypes = []any{
	(IntervalUnit)(0),              // 0: trader.strategy.v1.IntervalUnit
	(Side)(0),                      // 1: trader.strategy.v1.Side
	(PositionSide)(0),              // 2: trader.strategy.v1.PositionSide
	(IntentKind)(0),                // 3: trader.strategy.v1.IntentKind
	(Capability)(0),                // 4: trader.strategy.v1.Capability
	(ErrorCode)(0),                 // 5: trader.strategy.v1.ErrorCode
	(*Error)(nil),                  // 6: trader.strategy.v1.Error
	(*Interval)(nil),               // 7: trader.strategy.v1.Interval
	(*DataRequirement)(nil),        // 8: trader.strategy.v1.DataRequirement
	(*StrategyDescriptor)(nil),     // 9: trader.strategy.v1.StrategyDescriptor
	(*Bar)(nil),                    // 10: trader.strategy.v1.Bar
	(*PositionSnapshot)(nil),       // 11: trader.strategy.v1.PositionSnapshot
	(*AccountSnapshot)(nil),        // 12: trader.strategy.v1.AccountSnapshot
	(*HandshakeRequest)(nil),       // 13: trader.strategy.v1.HandshakeRequest
	(*HandshakeResponse)(nil),      // 14: trader.strategy.v1.HandshakeResponse
	(*RunOpen)(nil),                // 15: trader.strategy.v1.RunOpen
	(*SessionStart)(nil),           // 16: trader.strategy.v1.SessionStart
	(*SessionEnd)(nil),             // 17: trader.strategy.v1.SessionEnd
	(*BarEvent)(nil),               // 18: trader.strategy.v1.BarEvent
	(*DescribedIntent)(nil),        // 19: trader.strategy.v1.DescribedIntent
	(*DescribedSignal)(nil),        // 20: trader.strategy.v1.DescribedSignal
	(*OnBarResponse)(nil),          // 21: trader.strategy.v1.OnBarResponse
	(*FillEvent)(nil),              // 22: trader.strategy.v1.FillEvent
	(*OnFillResponse)(nil),         // 23: trader.strategy.v1.OnFillResponse
	(*RunServerMessage)(nil),       // 24: trader.strategy.v1.RunServerMessage
	(*RunClientMessage)(nil),       // 25: trader.strategy.v1.RunClientMessage
	(*GetHistoryBarsRequest)(nil),  // 26: trader.strategy.v1.GetHistoryBarsRequest
	(*GetHistoryBarsResponse)(nil), // 27: trader.strategy.v1.GetHistoryBarsResponse
	nil,                            // 28: trader.strategy.v1.DescribedSignal.ValuesEntry
}
var file_strategy_proto_depIdxs = []int32{
	5,  // 0: trader.strategy.v1.Error.code:type_name -> trader.strategy.v1.ErrorCode
	0,  // 1: trader.strategy.v1.Interval.unit:type_name -> trader.strategy.v1.IntervalUnit
	7,  // 2: trader.strategy.v1.DataRequirement.interval:type_name -> trader.strategy.v1.Interval
	8,  // 3: trader.strategy.v1.StrategyDescriptor.requirements:type_name -> trader.strategy.v1.DataRequirement
	2,  // 4: trader.strategy.v1.PositionSnapshot.side:type_name -> trader.strategy.v1.PositionSide
	11, // 5: trader.strategy.v1.AccountSnapshot.positions:type_name -> trader.strategy.v1.PositionSnapshot
	9,  // 6: trader.strategy.v1.HandshakeRequest.strategy_descriptor:type_name -> trader.strategy.v1.StrategyDescriptor
	4,  // 7: trader.strategy.v1.HandshakeRequest.capabilities:type_name -> trader.strategy.v1.Capability
	4,  // 8: trader.strategy.v1.HandshakeResponse.capabilities:type_name -> trader.strategy.v1.Capability
	6,  // 9: trader.strategy.v1.HandshakeResponse.reject_reason:type_name -> trader.strategy.v1.Error
	5,  // 10: trader.strategy.v1.SessionEnd.code:type_name -> trader.strategy.v1.ErrorCode
	7,  // 11: trader.strategy.v1.BarEvent.interval:type_name -> trader.strategy.v1.Interval
	10, // 12: trader.strategy.v1.BarEvent.bar:type_name -> trader.strategy.v1.Bar
	12, // 13: trader.strategy.v1.BarEvent.account:type_name -> trader.strategy.v1.AccountSnapshot
	3,  // 14: trader.strategy.v1.DescribedIntent.kind:type_name -> trader.strategy.v1.IntentKind
	1,  // 15: trader.strategy.v1.DescribedIntent.side:type_name -> trader.strategy.v1.Side
	28, // 16: trader.strategy.v1.DescribedSignal.values:type_name -> trader.strategy.v1.DescribedSignal.ValuesEntry
	19, // 17: trader.strategy.v1.OnBarResponse.intents:type_name -> trader.strategy.v1.DescribedIntent
	20, // 18: trader.strategy.v1.OnBarResponse.signals:type_name -> trader.strategy.v1.DescribedSignal
	6,  // 19: trader.strategy.v1.OnBarResponse.error:type_name -> trader.strategy.v1.Error
	1,  // 20: trader.strategy.v1.FillEvent.side:type_name -> trader.strategy.v1.Side
	12, // 21: trader.strategy.v1.FillEvent.account:type_name -> trader.strategy.v1.AccountSnapshot
	6,  // 22: trader.strategy.v1.OnFillResponse.error:type_name -> trader.strategy.v1.Error
	16, // 23: trader.strategy.v1.RunServerMessage.session_start:type_name -> trader.strategy.v1.SessionStart
	18, // 24: trader.strategy.v1.RunServerMessage.bar_event:type_name -> trader.strategy.v1.BarEvent
	22, // 25: trader.strategy.v1.RunServerMessage.fill_event:type_name -> trader.strategy.v1.FillEvent
	17, // 26: trader.strategy.v1.RunServerMessage.session_end:type_name -> trader.strategy.v1.SessionEnd
	15, // 27: trader.strategy.v1.RunClientMessage.run_open:type_name -> trader.strategy.v1.RunOpen
	21, // 28: trader.strategy.v1.RunClientMessage.on_bar_response:type_name -> trader.strategy.v1.OnBarResponse
	23, // 29: trader.strategy.v1.RunClientMessage.on_fill_response:type_name -> trader.strategy.v1.OnFillResponse
	7,  // 30: trader.strategy.v1.GetHistoryBarsRequest.interval:type_name -> trader.strategy.v1.Interval
	10, // 31: trader.strategy.v1.GetHistoryBarsResponse.bars:type_name -> trader.strategy.v1.Bar
	13, // 32: trader.strategy.v1.StrategyHostService.Handshake:input_type -> trader.strategy.v1.HandshakeRequest
	25, // 33: trader.strategy.v1.StrategyHostService.Run:input_type -> trader.strategy.v1.RunClientMessage
	26, // 34: trader.strategy.v1.StrategyHostService.GetHistoryBars:input_type -> trader.strategy.v1.GetHistoryBarsRequest
	14, // 35: trader.strategy.v1.StrategyHostService.Handshake:output_type -> trader.strategy.v1.HandshakeResponse
	24, // 36: trader.strategy.v1.StrategyHostService.Run:output_type -> trader.strategy.v1.RunServerMessage
	27, // 37: trader.strategy.v1.StrategyHostService.GetHistoryBars:output_type -> trader.strategy.v1.GetHistoryBarsResponse
	35, // [35:38] is the sub-list for method output_type
	32, // [32:35] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_strategy_proto_init() }
func file_strategy_proto_init() {
	if File_strategy_proto != nil {
		return
	}
	file_strategy_proto_msgTypes[18].OneofWrappers = []any{
		(*RunServerMessage_SessionStart)(nil),
		(*RunServerMessage_BarEvent)(nil),
		(*RunServerMessage_FillEvent)(nil),
		(*RunServerMessage_SessionEnd)(nil),
	}
	file_strategy_proto_msgTypes[19].OneofWrappers = []any{
		(*RunClientMessage_RunOpen)(nil),
		(*RunClientMessage_OnBarResponse)(nil),
		(*RunClientMessage_OnFillResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_proto_depIdxs,
		EnumInfos:         file_strategy_proto_enumTypes,
		MessageInfos:      file_strategy_proto_msgTypes,
	}.Build()
	File_strategy_proto = out.File
	file_strategy_proto_goTypes = nil
	file_strategy_proto_depIdxs = nil
}
