// Strategy Protocol v1 (issue #377, ADR-062).
//
// This schema is the wire boundary for an out-of-process external
// strategy: the Trader host process is the gRPC server
// (StrategyHostService); an external strategy process is the gRPC
// client that dials in over a Unix-domain socket. See ADR-062
// (docs/arch/adr-062-external-strategy-protocol-v1.org) for the full
// architecture and the reasoning behind every decision restated in
// comments below.
//
// Nothing in this file names a Trader domain type directly (order.
// Intent, instrument.ID, num.Price, and so on): every field here is a
// deliberately narrow wire representation of the piece of a domain
// value this protocol actually needs to carry, translated by a
// conversion layer outside this package (issue #378) — never a
// generated alias standing in for the domain type itself
// (package-boundaries.org rule 7).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: strategy.proto

package strategyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StrategyHostService_Handshake_FullMethodName      = "/trader.strategy.v1.StrategyHostService/Handshake"
	StrategyHostService_Run_FullMethodName            = "/trader.strategy.v1.StrategyHostService/Run"
	StrategyHostService_GetHistoryBars_FullMethodName = "/trader.strategy.v1.StrategyHostService/GetHistoryBars"
)

// StrategyHostServiceClient is the client API for StrategyHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StrategyHostService is implemented by the Trader host process
// (ExternalStrategyAdapter, issue #379) and called by an external
// strategy process (strategysdk, issue #381) as the gRPC client —
// ADR-062's own corrected topology, resolving GetHistoryBars's RPC
// direction without a second connection or host-side callback
// service.
type StrategyHostServiceClient interface {
	// Handshake is called once, before Run, carrying no run-scoped
	// values (above). Its response's own session_id is what Run and
	// GetHistoryBars are bound to.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Run is the guest-opened, bidirectional, long-lived session
	// stream (above), opened with the session_id Handshake issued via
	// RunOpen, its own mandatory first message. Exactly one Run stream
	// exists per Handshake'd connection — v1 assumes one strategy
	// identity per connection (ADR-062's own "one external strategy
	// process per host connection" scope statement).
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunClientMessage, RunServerMessage], error)
	// GetHistoryBars is callable at any time a callback is in flight,
	// independent of the Run stream's own message pump (above), and
	// must name the same session_id Handshake issued.
	GetHistoryBars(ctx context.Context, in *GetHistoryBarsRequest, opts ...grpc.CallOption) (*GetHistoryBarsResponse, error)
}

type strategyHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyHostServiceClient(cc grpc.ClientConnInterface) StrategyHostServiceClient {
	return &strategyHostServiceClient{cc}
}

func (c *strategyHostServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, StrategyHostService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyHostServiceClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunClientMessage, RunServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StrategyHostService_ServiceDesc.Streams[0], StrategyHostService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunClientMessage, RunServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StrategyHostService_RunClient = grpc.BidiStreamingClient[RunClientMessage, RunServerMessage]

func (c *strategyHostServiceClient) GetHistoryBars(ctx context.Context, in *GetHistoryBarsRequest, opts ...grpc.CallOption) (*GetHistoryBarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryBarsResponse)
	err := c.cc.Invoke(ctx, StrategyHostService_GetHistoryBars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyHostServiceServer is the server API for StrategyHostService service.
// All implementations must embed UnimplementedStrategyHostServiceServer
// for forward compatibility.
//
// StrategyHostService is implemented by the Trader host process
// (ExternalStrategyAdapter, issue #379) and called by an external
// strategy process (strategysdk, issue #381) as the gRPC client —
// ADR-062's own corrected topology, resolving GetHistoryBars's RPC
// direction without a second connection or host-side callback
// service.
type StrategyHostServiceServer interface {
	// Handshake is called once, before Run, carrying no run-scoped
	// values (above). Its response's own session_id is what Run and
	// GetHistoryBars are bound to.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Run is the guest-opened, bidirectional, long-lived session
	// stream (above), opened with the session_id Handshake issued via
	// RunOpen, its own mandatory first message. Exactly one Run stream
	// exists per Handshake'd connection — v1 assumes one strategy
	// identity per connection (ADR-062's own "one external strategy
	// process per host connection" scope statement).
	Run(grpc.BidiStreamingServer[RunClientMessage, RunServerMessage]) error
	// GetHistoryBars is callable at any time a callback is in flight,
	// independent of the Run stream's own message pump (above), and
	// must name the same session_id Handshake issued.
	GetHistoryBars(context.Context, *GetHistoryBarsRequest) (*GetHistoryBarsResponse, error)
	mustEmbedUnimplementedStrategyHostServiceServer()
}

// UnimplementedStrategyHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyHostServiceServer struct{}

func (UnimplementedStrategyHostServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedStrategyHostServiceServer) Run(grpc.BidiStreamingServer[RunClientMessage, RunServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedStrategyHostServiceServer) GetHistoryBars(context.Context, *GetHistoryBarsRequest) (*GetHistoryBarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryBars not implemented")
}
func (UnimplementedStrategyHostServiceServer) mustEmbedUnimplementedStrategyHostServiceServer() {}
func (UnimplementedStrategyHostServiceServer) testEmbeddedByValue()                             {}

// UnsafeStrategyHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyHostServiceServer will
// result in compilation errors.
type UnsafeStrategyHostServiceServer interface {
	mustEmbedUnimplementedStrategyHostServiceServer()
}

func RegisterStrategyHostServiceServer(s grpc.ServiceRegistrar, srv StrategyHostServiceServer) {
	// If the following call panics, it indicates UnimplementedStrategyHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategyHostService_ServiceDesc, srv)
}

func _StrategyHostService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyHostServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyHostService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyHostServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyHostService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StrategyHostServiceServer).Run(&grpc.GenericServerStream[RunClientMessage, RunServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StrategyHostService_RunServer = grpc.BidiStreamingServer[RunClientMessage, RunServerMessage]

func _StrategyHostService_GetHistoryBars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryBarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyHostServiceServer).GetHistoryBars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyHostService_GetHistoryBars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyHostServiceServer).GetHistoryBars(ctx, req.(*GetHistoryBarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StrategyHostService_ServiceDesc is the grpc.ServiceDesc for StrategyHostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategyHostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trader.strategy.v1.StrategyHostService",
	HandlerType: (*StrategyHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _StrategyHostService_Handshake_Handler,
		},
		{
			MethodName: "GetHistoryBars",
			Handler:    _StrategyHostService_GetHistoryBars_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _StrategyHostService_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "strategy.proto",
}
